# Generated by Django 5.2.12 on 2026-03-09 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='color_principal',
            field=models.CharField(default='#3C4623', max_length=7),
        ),
        migrations.AddField(
            model_name='negocio',
            name='color_secundario',
            field=models.CharField(default='#E8E4D9', max_length=7),
        ),
        migrations.AddField(
            model_name='negocio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='moneda',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombre_comercial',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
