# Generated by Django 5.2.12 on 2026-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_negocio_color_principal_negocio_color_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
