# Generated by Django 5.2.12 on 2026-03-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria_insumos',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rif_nit', models.CharField(blank=True, max_length=25, null=True)),
                ('moneda_base', models.CharField(default='USD', max_length=10)),
                ('color_primario', models.CharField(default='#A3E635', max_length=7)),
                ('color_secundario', models.CharField(default='#1a1c14', max_length=7)),
                ('modo_oscuro', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'negocios',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(default='Insumo', max_length=30)),
                ('unidad_medida', models.CharField(max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_costo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.categoriainsumo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.negocio')),
            ],
            options={
                'db_table': 'insumos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='backend.insumo')),
            ],
            options={
                'db_table': 'historial_precios',
            },
        ),
        migrations.AddField(
            model_name='categoriainsumo',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='backend.negocio'),
        ),
        migrations.CreateModel(
            name='ProductoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requiere_preparacion', models.BooleanField(default=False)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.negocio')),
            ],
            options={
                'db_table': 'productos_menu',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='backend.productomenu')),
            ],
            options={
                'db_table': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(default='Abierta', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.negocio')),
            ],
            options={
                'db_table': 'sesiones_caja',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='backend.sesioncaja')),
            ],
            options={
                'db_table': 'movimientos_caja',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(default='Cajero', max_length=20)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='backend.negocio')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuario'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.insumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuario')),
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
    ]
